GET http://localhost:8080/products

###

GET http://localhost:8080/products/123

###

PUT http://localhost:8080/products/123
Content-Type: application/json

{
  "name": "name changed",
  "description": "description changed"
}

###

POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "My other Product",
  "description": "hu?"
}

###

DELETE http://localhost:8080/products/123



